export const authConstants = {
    LOGIN_REQUEST : 'LOGIN_REQUEST',
    LOGIN_FAILURE : 'LOGIN_FAILURE',
    LOGIN_SUCCESSS : 'LOGIN_SUCCESSS',
    LOGOUT_REQUEST : 'LOGOUT_REQUEST',
    LOGOUT_SUCESS : 'LOGOUT_SUCESS',
    LOGOUT_FAILURE : 'LOGOUT_FAILURE'
   
}

export const userConstants = {
    USER_REGISTER_REQUEST : 'USER_REGISTER_REQUEST',
    USER_REGISTER_SUCCESS : ' USER_REGISTER_SUCCESS',
    USER_REGISTER_FAILURE : ' USER_REGISTER_FAILURE'
}